export function errorTranslate(key: string): string {
    if (typeof errorText[key] === 'string') {
        return errorText[key] as string;
    } else {
        return key;
    }
}

export const errorText: Record<string, string> = {
    API_ERROR_ACCESS_DENIED: 'Access denied',
    API_ERROR_WRONG_APP_KEY: 'Wrong API app key',
    API_ERROR_INCORRECT_INPUT_DATA: 'Please check the entered data',
    API_ERROR_INTERNAL_SERVER_ERROR: 'Problem with processing your request',
    API_ERROR_WRONG_INPUT: 'Wrong input data',
    API_ERROR_WRONG_INPUT_TEXT: 'Invalid text data, please do not use special characters',
    API_ERROR_INCORRECT_EMAIL_OR_PASSWORD: 'This email is not registered. Please try another one or Create an account',
    API_ERROR_USER_NOT_FOUND_BY_EMAIL: 'This email is not registered. Please try another one or Create an account',
    API_ERROR_WRONG_INPUT_EMAIL: 'Enter valid email address (ex. name@email.com)',
    API_ERROR_WRONG_INPUT_PASSWORD: 'Password is not strong enough',
    API_ERROR_WRONG_INPUT_PHONE: 'Enter valid phone number in the international format (ex. +11234567890)',
    API_ERROR_NOT_IMPLEMENTED: 'API is not implemented on server side',
    API_ERROR_EMAIL_ALREADY_REGISTERED: 'Email is already registered. Please check the entered data',
    API_ERROR_USER_CREDENTIAL_NOT_FOUND: 'This user do not have password',
    API_ERROR_EMAIL_ALREADY_VERIFIED: 'Your email is already verified',
    API_ERROR_PASSWORD_NOT_MATCH: 'You’ve entered an incorrect current password',
    API_ERROR_OTP_CODE_EXPIRED: 'This code is incorrect or expired. Please try another one or Resend the code',
    API_ERROR_WRONG_PASSWORD_RECOVERY_TOKEN: 'Recovery token is wrong',
    API_ERROR_PASSWORD_RECOVERY_TOKEN_EXPIRED:
        'Your recovery token is incorrect or has expired, please request a new one',
    API_ERROR_USER_EMAIL_IS_NOT_VERIFIED: 'You should verify your email first',
    API_ERROR_ACCOUNT_INACTIVE: 'This account is no longer active',
    API_ERROR_IMAGE_FILE_REQUIRED: 'Please select an image file',
    API_ERROR_WRONG_IMAGE_FORMAT: 'Your image should be .JPG or .PNG format',
    API_ERROR_FILE_TOO_LARGE: 'The file is too large',
    API_ERROR_EMAIL_INCORRECT: 'Email is incorrect. Please check the entered data.',
    API_ERROR_USER_NOT_FOUND: 'This email is not registered. Please try another one or Create an account',
    API_ERROR_EMAIL_WRONG: 'This email is not correct. Please try another one',
    API_ERROR_NOT_OWNER_OF_ASSIGNMENT: 'Not owner of assignment or assignment alredy accepted',
    API_ERROR_ASSIGNMENT_NOT_FOUND: 'Assignment Not found',
    API_ERROR_NEWS_DELETED_OR_ACCPETED: 'News Deleted or already accepted',
    API_ERROR_SUBMISSION_NOT_FOUND: 'Submission not found',
    API_ERROR_EXCEEDED_LIMIT_OF_FILES: 'You cannot upload more than 10 files!',
    API_ERROR_NEWS_CHANNEL_NOT_FOUND: 'News Channel not found',
    API_ERROR_NEWS_NOT_FOUND: 'News not found',
    API_ERROR_NEW_PASSWORD_EQUAL_CURRENT: 'Your new password cannot be equal the current one',
    API_ERROR_NEWS_ROOM_NOT_FOUND: 'News room not found',
    API_ERROR_MEDIA_TYPE_NOT_ALLOWED: 'This media type is not allowed',
    API_ERROR_DELETED_USER_ACCOUNT: 'This user has been deleted',
    API_ERROR_WRONG_PASSWORD: 'Please, try one more time, the password or email is wrong.',
    API_ERROR_NO_FILES_IN_SUBMISSION: 'No media files was found in submission!',
    API_ERROR_VIDEO_TOO_LONG: 'Video should be less than 120 sec.',
    API_ERROR_SUBMISSION_NOT_ACCEPTED: 'Submission not accepted.',
    API_ERROR_USER_NAME_ALREADY_TAKEN: 'This username already exists. Please try another one.',
    API_ERROR_USER_LOCATION_OUT_OF_RANGE:
        "Sorry, you can't create a submission, for using this option your location should be in USA",
    API_ERROR_CATEGORY_NOT_FOUND: 'Category not found',
    API_ERROR_CATEGORY_EXISTS: 'Category with this title already exists',
    API_ERROR_SUBMISSION_DISTANCE_WRONG: 'Distance for submissions is too far, please try to be closer and try again',
    API_ERROR_COMPANY_NOT_FOUND: 'Company not found or you dont have permission',
    API_ERROR_BRANCH_NOT_FOUND: 'Branch not found',
    API_ERROR_INVITATION_ALREADY_EXISTS: 'This invitation is already exists',
    API_ERROR_PHONE_ALREADY_REGISTERED: 'Phone is already registered. Please check the entered data',
    API_ERROR_ROLE_NOT_FOUND: 'Role not found',
    API_ERROR_ALREADY_MEMBER: 'User is already member',
    API_ERROR_BUILDING_NOT_FOUND: 'Building not found or you dont have permission',
    API_ERROR_APARTMENT_NOT_FOUND: 'Apartment not found or you dont have permission',
    API_ERROR_UNIT_NOT_FOUND: 'Unit not found or you dont have permission',
    API_ERROR_ROOM_NOT_FOUND: 'Room not found or you dont have permission',
    API_ERROR_SIGNY_CONTACT_NOT_FOUND: 'You provided not existing contact',
    API_ERROR_SIGNY_GROUP_NOT_FOUND: 'You provided not existing group',
    API_ERROR_SIGNY_DOCUMENT_NOT_FOUND: 'Document not found or you don`t have enough permission',
    API_ERROR_CONTACT_WITH_SUCH_EMAIL_EXISTS: 'Contact with such email already exists',
    API_ERROR_CONTACT_WITH_SUCH_PHONE_EXISTS: 'Contact with such phone already exists',
    API_ERROR_CONTACT_WITH_SUCH_WHATSAPP_EXISTS: 'Contact with such whatsapp already exists',
    API_ERROR_CONTACT_WITH_SUCH_TELEGRAM_EXISTS: 'Contact with such telegram already exists',
    API_ERROR_CONTACT_WITH_SUCH_TELEGRAM_NICK_NAME_EXISTS: 'Contact with such telegram nickname already exists',
    API_ERROR_SIGNY_INPUT_NOT_FOUND: 'Input not found or you don`t have enough permission',
    API_ERROR_USER_NOT_EXIST: 'User not exist',
    API_ERROR_SIGNATORY_EXISTS: 'Signatory already exists',
    API_ERROR_SIGNY_EMAIL_TEMPLATE_NOT_FOUND: 'Signy email template not found or you don`t have enough permission',
    API_ERROR_SMS_INFO_NOT_FOUND: 'Sms info template not found',
    API_ERROR_SIGNATORY_NOT_FOUND: 'Signer not found',
    API_ERROR_PASS_CODE_NOT_FOUND: 'Provide password please',
    API_ERROR_INVALID_PASS_CODE: 'Provided password is invalid',
    API_ERROR_USER_PHONE_IS_NOT_VERIFIED: 'You should verify your phone first',
    API_ERROR_INVALID_PHONE_NUMBER_FOR_ISRAEL: 'Registration by Phone number is possible only for Israeli numbers',
    API_ERROR_SUBSCRIPTION_PLAN_NOT_FOUND: 'Subscription plan not found, please change plan',
    API_ERROR_COUPON_NOT_FOUND: 'Coupon not found',
    API_ERROR_SIGNATURE_PASSWORD_NOT_EXISTS: 'You already have been here!:) please create password first',
    API_ERROR_TEMPLATE_NOT_FOUND: 'Template not found',
    API_ERROR_UPGRADE_PLAN_FOR_DOCUMENTS:
        'You reached maximum amount of documents count, please upgrade plan for uploading more',
    API_ERROR_UPGRADE_PLAN_FOR_TEMPLATES:
        'You reached maximum amount of templates count, please upgrade plan for uploading more',
    API_ERROR_UPGRADE_PLAN_FOR_SMS: 'You reached maximum amount of sms count, please upgrade plan for sending more',
    API_ERROR_UPGRADE_PLAN_FOR_STORAGE:
        'You reached maximum amount of storage capacity, please upgrade plan for uploading more',
    API_ERROR_DOCUMENT_ALREADY_SHARED_TO_SIGNATORY: 'Document already shared with this user',
};
